# Data Profiling
## Indonesia Palm Oil Supply Chain

### Tujuan

Notebook ini digunakan untuk melakukan profiling awal terhadap
dataset Indonesia palm oil - Supply chain data dari Trase.

Profiling dilakukan untuk memahami ukuran, struktur, kualitas,
distribusi, serta karakteristik temporal dan geografis dataset
sebelum proses data cleaning.

Hasil profiling digunakan sebagai dasar untuk menentukan proses
cleaning pada notebook `02_data_cleaning.ipynb`.

In [3]:
import polars as pl
import duckdb

In [17]:
DATA_PATH = "../data/raw/indonesia_palm_oil_v1_2_5.csv"

DATA_PATH

'../data/raw/indonesia_palm_oil_v1_2_5.csv'

In [18]:
df = pl.scan_csv(DATA_PATH)

df

In [19]:
df.collect_schema()

Schema([('year', Int64),
        ('country_of_production', String),
        ('product_type', String),
        ('forest_500_palm_oil', String),
        ('zero_deforestation_indonesia_palm_oil', String),
        ('province_of_production', String),
        ('kabupaten_of_production', String),
        ('mill', String),
        ('mill_trase_id', String),
        ('mill_group', String),
        ('refinery', String),
        ('refinery_trase_id', String),
        ('refinery_group', String),
        ('exporter', String),
        ('exporter_group', String),
        ('port_of_export', String),
        ('importer', String),
        ('importer_group', String),
        ('country_of_first_import', String),
        ('economic_bloc', String),
        ('province_of_production_trase_id', String),
        ('kabupaten_of_production_trase_id', String),
        ('country_of_production_trase_id', String),
        ('country_of_first_import_trase_id', String),
        ('palm_oil_deforestation_10_year_total_exposure', String),
        ('palm_oil_deforestation_annual_exposure', String),
        ('total_emission_exposure', String),
        ('net_emission_luc_exposure', String),
        ('emission_subsidence_exposure', String),
        ('gross_emission_luc_exposure', String),
        ('emissions_fire_on_peat_exposure', String),
        ('volume', Float64),
        ('oil_palm_ha', String),
        ('fob', String)])

In [20]:
row_count = df.select(pl.len()).collect()

row_count

shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 1694907 │
└─────────┘

In [22]:
column_count = len(df.collect_schema())

column_count

34

In [23]:
df.head(5).collect()

shape: (5, 34)
┌──────┬──────────────┬──────────────┬─────────────┬───┬─────────────┬────────┬─────────────┬──────┐
│ year ┆ country_of_p ┆ product_type ┆ forest_500_ ┆ … ┆ emissions_f ┆ volume ┆ oil_palm_ha ┆ fob  │
│ ---  ┆ roduction    ┆ ---          ┆ palm_oil    ┆   ┆ ire_on_peat ┆ ---    ┆ ---         ┆ ---  │
│ i64  ┆ ---          ┆ str          ┆ ---         ┆   ┆ _exposur…   ┆ f64    ┆ str         ┆ str  │
│      ┆ str          ┆              ┆ str         ┆   ┆ ---         ┆        ┆             ┆      │
│      ┆              ┆              ┆             ┆   ┆ str         ┆        ┆             ┆      │
╞══════╪══════════════╪══════════════╪═════════════╪═══╪═════════════╪════════╪═════════════╪══════╡
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 22.8   ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 3000.0 ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 1000.0 ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 1000.0 ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 500.0  ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
└──────┴──────────────┴──────────────┴─────────────┴───┴─────────────┴────────┴─────────────┴──────┘

In [24]:
null_counts = df.select(
    pl.all().null_count()
).collect()

null_counts

shape: (1, 34)
┌──────┬──────────────┬─────────────┬─────────────┬───┬─────────────┬────────┬─────────────┬───────┐
│ year ┆ country_of_p ┆ product_typ ┆ forest_500_ ┆ … ┆ emissions_f ┆ volume ┆ oil_palm_ha ┆ fob   │
│ ---  ┆ roduction    ┆ e           ┆ palm_oil    ┆   ┆ ire_on_peat ┆ ---    ┆ ---         ┆ ---   │
│ u32  ┆ ---          ┆ ---         ┆ ---         ┆   ┆ _exposur…   ┆ u32    ┆ u32         ┆ u32   │
│      ┆ u32          ┆ u32         ┆ u32         ┆   ┆ ---         ┆        ┆             ┆       │
│      ┆              ┆             ┆             ┆   ┆ u32         ┆        ┆             ┆       │
╞══════╪══════════════╪═════════════╪═════════════╪═══╪═════════════╪════════╪═════════════╪═══════╡
│ 0    ┆ 0            ┆ 0           ┆ 0           ┆ … ┆ 1025290     ┆ 0      ┆ 10233       ┆ 10957 │
└──────┴──────────────┴─────────────┴─────────────┴───┴─────────────┴────────┴─────────────┴───────┘

In [25]:
year_summary = (
    df
    .group_by("year")
    .agg(pl.len().alias("total_records"))
    .sort("year")
    .collect()
)

year_summary

shape: (10, 2)
┌──────┬───────────────┐
│ year ┆ total_records │
│ ---  ┆ ---           │
│ i64  ┆ u32           │
╞══════╪═══════════════╡
│ 2013 ┆ 2095          │
│ 2014 ┆ 2056          │
│ 2015 ┆ 2038          │
│ 2016 ┆ 2213          │
│ 2017 ┆ 1831          │
│ 2018 ┆ 247986        │
│ 2019 ┆ 318343        │
│ 2020 ┆ 448728        │
│ 2021 ┆ 385389        │
│ 2022 ┆ 284228        │
└──────┴───────────────┘

## Kesimpulan Profiling Awal

Berdasarkan profiling awal, dataset memiliki lebih dari satu juta
baris sehingga memenuhi persyaratan ukuran dataset pada Milestone 1.

Dataset memiliki 34 kolom dan mencakup data tahun 2013–2022.
Pemeriksaan awal juga dilakukan terhadap struktur kolom, contoh data,
dan missing values.

Hasil profiling ini akan digunakan sebagai dasar untuk proses cleaning
pada `02_data_cleaning.ipynb` pada Milestone 2.